from typing import List

from pydantic import BaseModel, Field


# ==========================================================
# Task 1 - Ticket Triage
# ==========================================================

class TicketInput(BaseModel):
    """
    Incoming support ticket.
    """

    subject: str
    body: str


class TicketTriageResponse(BaseModel):
    """
    Structured response generated by the AI Ticket Triage Agent.
    """

    product_area: str = Field(
        description="Product module affected"
    )

    issue_category: str = Field(
        description="Bug, Billing, Performance, Integration, etc."
    )

    urgency: str = Field(
        description="Priority level P1-P4"
    )

    reasoning: str = Field(
        description="Why this classification was selected"
    )

    knowledge_base_article: str = Field(
        description="Most relevant KB document"
    )

    responder_team: str = Field(
        description="Recommended support team"
    )

    first_response: str = Field(
        description="Draft first customer response"
    )


# ==========================================================
# Task 2 - Account Summary
# ==========================================================

class RiskItem(BaseModel):

    risk: str

    evidence: str


class AccountSummaryResponse(BaseModel):
    """
    Structured TAM Summary
    """

    executive_summary: str

    open_risks: List[RiskItem]

    talking_points: List[str]